import { DexEntry } from "../dex/models/dex-entry";

export class ExampleDexEntries {
  static dexEntries: DexEntry[] = [
    new DexEntry(0,   'Mining Truck'),
    new DexEntry(1,   'Auto Turret'),
    new DexEntry(2,   'Anti-Armor Pod'),
    new DexEntry(3,   'Assault Troopers'),
    new DexEntry(4,   'Mortar Men'),
    new DexEntry(5,   'Decon ATV'),
    new DexEntry(6,   'Crusader ATV'),
    new DexEntry(7,   'Shepard Tank'),
    new DexEntry(8,   'SAM Tank'),
    new DexEntry(9,   'Spitfire Chopper'),
    new DexEntry(10,  'Seraphim'),
    new DexEntry(11,  'Ghosts'),
    new DexEntry(12,  'Brimstone Artillery'),
    new DexEntry(13,  'Enabler'),
    new DexEntry(14,  'Pulsar Tower'),
    new DexEntry(15,  'Anti-Air Platform'),
    new DexEntry(16,  'Sentinel'),
    new DexEntry(17,  'Sentry Bots'),
    new DexEntry(18,  'Wheel Drones'),
    new DexEntry(19,  'Keeper Tank'),
    new DexEntry(20,  'Pulsar Tank'),
    new DexEntry(21,  'Synergizer'),
    new DexEntry(22,  'Strafer Jet'),
    new DexEntry(23,  'Amplifier'),
    new DexEntry(24,  'Hunter Probe'),
    new DexEntry(25,  'Pulsar Cruiser'),
    new DexEntry(26,  'Heavy Destroyer'),
    new DexEntry(27,  'Phage'),
    new DexEntry(28,  'Tendril Pod'),
    new DexEntry(29,  'Reaper Spine'),
    new DexEntry(30,  'Swarmenvash'),
    new DexEntry(31,  'Scraper'),
    new DexEntry(32,  'Tormenvash'),
    new DexEntry(33,  'Glutton'),
    new DexEntry(34,  'Necrovash'),
    new DexEntry(35,  'Harbinger'),
    new DexEntry(36,  'Screachers'),
    new DexEntry(37,  'Blight Spitter'),
    new DexEntry(38,  'Spawn Pit'),
    new DexEntry(39,  'Nestlings'),
    new DexEntry(40,  'Slayer'),
    new DexEntry(41,  'Swarm Queen'),
    new DexEntry(42,  'Shadow Hive'),
    new DexEntry(43,  'Hiveling'),
    new DexEntry(44,  'Titanipede'),
  ];
}