// igx icon names
export enum DexoIcon {
  AccountCircle = 'account_circle',
  Error = 'error',
  GroupWork = 'group_work',
  ListAlt = 'list_alt',
  Upload = 'upload',
  Download = 'download',
  Menu = 'menu',
  Close = 'close',
  Edit = 'edit',
  Add = 'add_circle',
  Drag = 'drag_indicator',
  Expand = 'unfold_more',
  Collapse = 'unfold_less',
  OpenArrow = 'keyboard_arrow_right',
  CloseArrow = 'keyboard_arrow_left',
  Image = 'image',
  TextFields = 'text_fields',
  PhotoLibrary = 'photo_library',
  List = 'list',
}